### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by daswetter73** [meanttobehere/just-first-project#1]
1. Использовать модификатор ключ-значение, когда важно значение модификатора. Неверно: &_size-ss
2. Неверное использование модификатора .calendar__grid-item_arrival-departure-date, тк название модификатора должно характеризовать внешний вид, состояние или поведение 
3. Из названия не понятно, что это за штука: not-current-month-date, field
4. Один блок = одна папка. Неверно: в checkbox-list, dropdown
5. Глобальные стили вынести в отдельный файл

**Comment by meanttobehere** [comment]
> 5. Глобальные стили вынести в отдельный файл

Глобальные переменные в resources/style.scss. Что нужно еще вынести в отдельный файл?

**Comment by meanttobehere** [comment]
> 1. Использовать модификатор ключ-значение, когда важно значение модификатора. Неверно: &_size-ss
В компоненте button не должно быть модификатора с ключом size? Или использовать без ключа button_ss?

**Comment by daswetter73** [comment]
Глобальные стили, к примеру, для html, body должны лежать в отдельном файле global.scss

**Comment by meanttobehere** [comment]
Вынес стили для тэгов html и body в отдельный файл. Готов к ревью.

**Comment by daswetter73** [comment]
Глобальные стили должны лежать только в файле global

**Comment by daswetter73** [comment]
1. Неправильное использование модификатора 'checkbox_rich', 'comfort-item_underlined'
2. Класс, не относящийся к блоку
![image](https://user-images.githubusercontent.com/92922078/143848676-8808f34f-8cd5-4e9e-9edd-87980356e35a.png)
3. В header осталась лишняя папка
4. Картинки должны именоваться в lower-case-hyphenated, иметь осмысленные названия, также названия не должны повторяться. К примеру, не review1, а имя-фамилия, если это фото человека.
5. Не перечислено запасное семейство шрифта
https://github.com/fullstack-development/front-end-best-practices/tree/master/CSS#3.5

**Comment by meanttobehere** [comment]
Все исправил
