### ISSUE TITLE
UI/UX

### ISSUE THREAD

**Issue by daswetter73** [meanttobehere/just-first-project#2]
1. В colors types разместить соответствующие цвета
2. Чекбокс и радиобаттон должны работать и при клике на label
3. Часть тени пропала

![image](https://user-images.githubusercontent.com/92922078/143034065-5210a53c-9169-4ca7-8fdf-2a4bac5b5a85.png)

**Comment by meanttobehere** [comment]
> 1. В colors types разместить соответствующие цвета
> 
> ![image](https://user-images.githubusercontent.com/92922078/143034065-5210a53c-9169-4ca7-8fdf-2a4bac5b5a85.png)

Не совсем понятно. Данные для генерации страницы в json файле , в том числе и цвета для компонентов color-item.

**Comment by daswetter73** [comment]
![image](https://user-images.githubusercontent.com/92922078/143196852-e40751c3-c94e-46e8-9dce-dc739232b1e7.png)

**Comment by meanttobehere** [comment]
done

**Comment by daswetter73** [comment]
1. Toggle тоже должен работать при клике на label
2. Тень все еще закрывается
![photo_2021-11-25_21-05-42](https://user-images.githubusercontent.com/92922078/143487463-33317b92-d38c-4c43-ae10-af4dd990ed7e.jpg)
3. На разрешениях меньше 768px футер должен быть такой
![image](https://user-images.githubusercontent.com/92922078/143487572-cbaa8760-b29b-4828-b113-451e7d501984.png)
4. Шрифт не соответствует представленному в проекте
![image](https://user-images.githubusercontent.com/92922078/143487601-48db63e3-875b-4fd1-af91-0105b291d90a.png)
5. На странице room details не работают лайки
6. В registration и sign-in неправильная картинка фона
7. Слайдер перекрывается
![Снимок экрана 2021-11-25 205841](https://user-images.githubusercontent.com/92922078/143487689-40ebb9d5-2330-492f-a88a-25af58603cad.png)
8. Делать отступ от краев для форм и тд
![Снимок экрана 2021-11-25 204647](https://user-images.githubusercontent.com/92922078/143487766-c85c13b1-5412-4d86-99ae-2e14f5129385.png)
9. Здесь лишний отступ
![Снимок экрана 2021-11-25 211753](https://user-images.githubusercontent.com/92922078/143487838-4897a641-00b4-4174-9103-8e257ba393e2.png)
10. Исправить недочеты в соответствии с pp, здесь лишь некоторые из них 
![Снимок экрана 2021-11-25 205145](https://user-images.githubusercontent.com/92922078/143487936-735be345-d146-49a6-9161-27a9192a6c3a.png)
![Снимок экрана 2021-11-25 205627](https://user-images.githubusercontent.com/92922078/143487939-0cef8489-b30e-45f6-91da-7b79ee264312.png)
![Снимок экрана 2021-11-25 205714](https://user-images.githubusercontent.com/92922078/143487941-60b38610-014a-4ba7-ac81-27e4d8688ae8.png)

**Comment by daswetter73** [comment]
1. Второе Text field показывает состояние при hover/focus, соответственно, первое должно работать так же
![image](https://user-images.githubusercontent.com/92922078/143848263-97470a70-39a5-4573-8dd7-cb8e716b4bc2.png)
2. Недочеты в pp
![image](https://user-images.githubusercontent.com/92922078/143848319-a439fc35-b1aa-4ef6-8ffd-73a427770104.png)
![image](https://user-images.githubusercontent.com/92922078/143848338-8de552a4-d73b-4754-aff7-0b864fe7a812.png)
3. Несовпадение формата
![image](https://user-images.githubusercontent.com/92922078/143848375-d390e92d-af0d-4971-8633-770a07c63fe2.png)
4. Описание тоже должно быть кликабельным
![image](https://user-images.githubusercontent.com/92922078/143848455-a4081d0c-be9c-456f-829f-36ada6090b8f.png)

**Comment by daswetter73** [comment]
Недочеты header
1. header на телефонах с низким экраном недоступны кнопки
![image](https://user-images.githubusercontent.com/92922078/144011090-ce2455ef-1802-4a6d-905f-bb07af46804d.png)
2. В планшетной версии header должен закрываться при клике на страницу

3.Съехали иконки соц сетей
![image](https://user-images.githubusercontent.com/92922078/144011153-9d789fbe-0b74-4cfb-8a9e-00b65d6b400d.png)

**Comment by daswetter73** [comment]
1. Список должен закрываться при нажатии вне, а также не должен влиять на положение следующих элементов
![image](https://user-images.githubusercontent.com/92922078/144553724-5a475292-71f4-45be-9dbe-b2439aaf86c5.png)

**Comment by daswetter73** [comment]
1. Наложение 
![image](https://user-images.githubusercontent.com/92922078/145003176-0c838a3d-d533-4614-bf6e-3bbd40a1a3ac.png)
2. До списка соглашений нельзя доскроллить
![image](https://user-images.githubusercontent.com/92922078/145003673-fcfae312-d155-46e5-b639-3226e44a1750.png)
3. Странные цвета
![image](https://user-images.githubusercontent.com/92922078/145004042-8120e87f-9a51-47b7-9adc-e9fdbe4dd06c.png)
4. Картинки должны себя вести так же, как на других страницах, те растягиваться по всей длине
![image](https://user-images.githubusercontent.com/92922078/145005296-b91fdb17-237d-46e1-9093-1ff0e36e32e4.png)

**Comment by daswetter73** [comment]
Непредсказуемое поведение хедера

https://user-images.githubusercontent.com/92922078/145457300-3e0143d5-4491-4973-8d89-babe08fa18be.mp4

https://user-images.githubusercontent.com/92922078/145457327-1d14f888-31b4-4099-9530-09cb42e0d344.mp4
