### ISSUE TITLE
Запуск

### ISSUE THREAD

**Issue by daswetter73** [meanttobehere/just-first-project#3]
При запуске программы, к примеру, через npm run watch должна открываться примерно такая страница:
![photo_2021-05-23_09-33-21](https://user-images.githubusercontent.com/92922078/143034870-f5540359-ae11-42d9-9282-ddd2aa26cfd5.jpg)

**Comment by daswetter73** [comment]
Не забывай про правила правильный именований коммитов к ишью. Когда будешь готов к следующей проверке, оставь комментарий "Готов к ревью"

**Comment by meanttobehere** [comment]
Добавил страницу navigation. Запуск через webpack-dev-server. Команда для запуска npm start.

**Comment by daswetter73** [comment]
1. Добавить в package.json webpack-dev-server
