### ISSUE TITLE
Структура

### ISSUE THREAD

**Issue by daswetter73** [meanttobehere/just-first-project#5]
Для страниц создать "шаблон" pug с head, title, favicons и тд, в который можно вставлять содержимое

**Comment by daswetter73** [comment]
1. Повторяющийся код (можно использовать each)
![image](https://user-images.githubusercontent.com/92922078/143849087-3a2f1833-69db-425c-8167-02fc73c81831.png)
2. В таких случаях лучше сразу назначать значение переменной.
К примеру, так
const class = [ 'дефолтное название класса', переменная && 'название класса']
И какую функцию играет isRich? Если только замена description, то почему бы не использовать его?
![image](https://user-images.githubusercontent.com/92922078/143849328-9ad2e570-99df-43a0-85bf-ff8daf6c362a.png)
3. Заменить файлы .css на .scss

**Comment by daswetter73** [comment]
1. Библиотеки лежат обычными файлами, а должны быть установлены через npm или yarn. (lib в range-slider)
2. Здесь тоже нужно использовать each. Нужно просмотреть проект и переработать повторяющийся код подобным образом.
![image](https://user-images.githubusercontent.com/92922078/144011481-3d74ee19-d848-4bd5-9f31-c1001c4cd378.png)
3. В файлах .json допустимо хранить слишком объемные данные, информацию, которая может помешать пониманию кода. Однако, в данном проекте использование большинства .json файлов излишне.

**Comment by daswetter73** [comment]
1. Еще раз про .json: использование .json оправдано, если на странице слишком объемные данные, к примеру, огромный текст на несколько страниц. Здесь же, все разбито на блоки и нет необходимости выносить в отдельный файл, тем более такие данные, как названия кнопок и ссылки
2. Повторяющиеся данные
https://github.com/meanttobehere/just-first-project/blob/e541927041fc3ecbf442b67538c46c1914a48638/src/components/hamburger/hamburger.pug#L3
3. В readme разделить на ui-kit и website pages, оставить ссылку на навигационную страницу, как в readme, так и в проекте, к примеру, при клике на логотип toxin
4. Не везде есть параметры по умолчанию
https://github.com/meanttobehere/just-first-project/blob/e541927041fc3ecbf442b67538c46c1914a48638/src/components/date-dropdown/date-dropdown.pug#L9
5. Мета тег viewport оформлен не по стандарту
https://github.com/fullstack-development/front-end-best-practices/tree/master/HTML#2.6
6. Не исправлено:
_В таких случаях лучше сразу назначать значение переменной.
К примеру, так_
`const class = [ 'дефолтное название класса', переменная && 'название класса']`
https://github.com/meanttobehere/just-first-project/blob/e541927041fc3ecbf442b67538c46c1914a48638/src/components/checkbox-list/checkbox-list.pug#L12
7. Внешнее позиционирование блока не разрешено
https://github.com/meanttobehere/just-first-project/blob/e541927041fc3ecbf442b67538c46c1914a48638/src/components/checkbox/checkbox.scss#L5
8. Название модификатора должно характеризовать внешний вид, состояние или поведение
https://github.com/meanttobehere/just-first-project/blob/57aade671f93d12e7a0f52f9a351a61f6452b53b/src/components/room-card/room-card.scss#L36
9. Оставлен "закомменченый" код
https://github.com/meanttobehere/just-first-project/blob/f2fd5c5efbab8527d264b99755fdaf2cdf324683/src/components/field/Field.js#L12

**Comment by meanttobehere** [comment]
Все исправил

**Comment by daswetter73** [comment]
1. Не везде исправлен код по пункту 6 из предыдущего комментария
https://github.com/meanttobehere/just-first-project/blob/001c0e08898cf00432381190264a3769bb7ece64/src/components/room-card/room-card.pug#L15
2. Нет префикса js 
https://github.com/meanttobehere/just-first-project/blob/f2fd5c5efbab8527d264b99755fdaf2cdf324683/src/pages/search-page/index.js#L3
3. Семантически неправильная конструкция a.button, то есть это ссылка, которая маскируется под button?
https://github.com/meanttobehere/just-first-project/blob/ffe0f04e36f93d0c175be906bb08d286be8e1699/src/components/button/button.pug#L19

**Comment by daswetter73** [comment]
1. Все еще пункт 6 не исправлен
_Лучше сразу назначать значение переменной._
https://github.com/meanttobehere/just-first-project/blob/658ed526b791366bb8fe83a77132fc19fe1d4686/src/components/footer/footer.pug#L43
